modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/TwistedGate/ImmersivePetroleum/issues"
license="All rights reserved"

[[mods]] #mandatory
	modId="immersivepetroleum"
	version="${version_ip}"
	displayName="Immersive Petroleum"
	displayURL="https://minecraft.curseforge.com/projects/immersive-petroleum"
	authors="Flaxbeard and Maintained by TwistedGate"
	description="Adds oil and oil processing features to Immersive Engineering."
	logoFile="logo.png"
	#updateJSONURL=""
	#credits=""

[[dependencies.immersivepetroleum]]
	modId="minecraft"
	type="required"
	versionRange="[${version_minecraft}]"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="neoforge"
	type="required"
	versionRange="[${version_neoforge},)"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="immersiveengineering"
	type="required"
	versionRange="[${version_ie},)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="jei"
	type="optional"
	versionRange="[${version_jei},)"
	ordering="NONE"
	side="BOTH"