modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/TwistedGate/ImmersivePetroleum/issues"
license="All rights reserved"

[[mods]] #mandatory
	modId="immersivepetroleum"
	version="${file.jarVersion}"
	displayName="Immersive Petroleum"
	displayURL="https://minecraft.curseforge.com/projects/immersive-petroleum"
	authors="Flaxbeard and Maintained by TwistedGate"
	description="Adds oil and oil processing features to Immersive Engineering."
	logoFile="logo.png"
	#updateJSONURL=""
	#credits=""

[[dependencies.immersivepetroleum]]
	modId="minecraft"
	type="required"
	versionRange="[${mc_version}]"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="neoforge"
	type="required"
	versionRange="[${neoforge_version},)"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="immersiveengineering"
	type="required"
	versionRange="[${ie_version},)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="jei"
	type="optional"
	versionRange="[${jei_version},)"
	ordering="NONE"
	side="BOTH"